### ISSUE TITLE
Error: Column `cell_type` is not found

### ISSUE THREAD

**Issue by jamesonholloman** [neurorestore/Libra#51]
Hi,

Thanks so much for this helpful tool! When I analyze my single nuclei dataset, I'm able to run pseudobulk and mixed model analyses through Libra but when I attempt to run a single cell analysis I receive an error message. I've listed two examples of code below demonstrating the successful running of the pseudobulk analysis and the error I receive with single cell.

> DE = run_de(oligos, meta = meta, de_family="pseudobulk",de_method="limma",de_type="voom")
[1] "1"

> DE = run_de(oligos, meta = meta, de_family="singlecell",de_method="wilcox")
Normalizing layer: counts
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
[1/1] working on cell type: 1 ...
object 'method' not foundError in `group_by()`:
! Must group by variables found in `.data`.
✖ Column `cell_type` is not found.

Any thoughts on why this is occurring?

**Comment by AlanTeoYueYang** [comment]
Hi, there was a minor bug that has been fixed.

**Comment by jamesonholloman** [comment]
Thanks for the reply! Unfortunately, I'm still getting the same error. I ran the check inputs function on my data and there were no errors so no sure what's causing the issue. 

> DE = run_de(d, de_family = 'pseudobulk', de_method = 'edgeR', de_type = 'QLF')
[1] "oligos"
> DE = run_de(d, de_family = 'singlecell', de_method = 'wilcox')
Normalizing layer: counts
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
[1/1] working on cell type: oligos ...
object 'method' not foundError in `group_by()`:
! Must group by variables found in `.data`.
✖ Column `cell_type` is not found.
Run `rlang::last_trace()` to see where the error occurred.

**Comment by igrisch** [comment]
I am having the same problem, even with the most updated version.

**Comment by dbyzy** [comment]
I also have the same problem

**Comment by AlanTeoYueYang** [comment]
Hi all,

Do you mind sharing with me your datasets so I can figure what might be wrong?

Best,
Alan

**Comment by vicsanga** [comment]
Same problem here
